from pathlib import Path
import re

demo=Path('demo')
admin=(demo/'admin.html').read_text(encoding='utf-8')
index=(demo/'index.html').read_text(encoding='utf-8')
css=(demo/'kol.css').read_text(encoding='utf-8')

admin=admin.replace("b.onclick=()=>showLibrary();\n navs[0].onclick=()=>showMenu();","b.onclick=()=>showLibrary();\n const orders=document.createElement('button'); orders.className='nav-btn'; orders.id='navOrders'; orders.innerHTML='▤ &nbsp; Bestillinger'; b.after(orders);\n const restaurant=document.createElement('button'); restaurant.className='nav-btn'; restaurant.id='navRestaurant'; restaurant.innerHTML='⚙ &nbsp; Restaurant'; orders.after(restaurant);\n orders.onclick=()=>showOrders(); restaurant.onclick=()=>showRestaurant();\n navs[0].onclick=()=>showMenu();")
admin=admin.replace("function setNav(which){$('#navProducts')?.classList.toggle('active',which==='menu');$('#navChoices')?.classList.toggle('active',which==='library')}","function setNav(which){$('#navProducts')?.classList.toggle('active',which==='menu');$('#navChoices')?.classList.toggle('active',which==='library');$('#navOrders')?.classList.toggle('active',which==='orders');$('#navRestaurant')?.classList.toggle('active',which==='restaurant')}")

extra=r'''
function orderArray(){const o=config.orders||{};return Array.isArray(o)?o.filter(Boolean):Object.entries(o).map(([id,v])=>({...v,id:v?.id||id})).filter(Boolean).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function orderStatusLabel(s){return ({mottatt:'Ny',tilberedning:'Tilberedes',klar:'Klar',hentet:'Hentet',avvist:'Avvist'})[s]||s||'Ny'}
function orderTime(v){if(!v)return '—';try{return new Date(v).toLocaleString('nb-NO',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(e){return '—'}}
function showOrders(){mode='orders';setNav('orders');closeEditor();$('.page-head h1').textContent='Bestillinger';$('.page-head p').textContent='Nye og aktive bestillinger fra kundesiden.';$('.tools').innerHTML='<button class="ghost" id="refreshOrders">↻ Oppdater</button>';$('#addCategoryBtn').hidden=true;$('#refreshOrders').onclick=()=>load();renderOrders()}
function renderOrders(){if(mode!=='orders')return;const orders=orderArray();const active=orders.filter(o=>!['hentet','avvist'].includes(o.status));root.innerHTML=`<div class="order-stats"><div><b>${active.length}</b><span>Aktive</span></div><div><b>${orders.filter(o=>o.status==='mottatt').length}</b><span>Nye</span></div><div><b>${orders.filter(o=>o.status==='klar').length}</b><span>Klare</span></div></div><div class="admin-orders">${orders.length?orders.map(orderCard).join(''):'<div class="library-empty"><strong>Ingen bestillinger</strong><p>Nye ordre vil vises her automatisk.</p></div>'}</div>`;$$('[data-order-status]').forEach(b=>b.onclick=()=>setOrderStatus(b.dataset.orderId,b.dataset.orderStatus))}
function orderCard(o){const items=arr(o.items||o.lines).map(x=>`${x.quantity||x.qty||1}× ${x.name||x.productName||'Produkt'}`).join(', ');return `<article class="admin-order-card"><div class="order-card-top"><div><span class="order-number">#${esc(String(o.id||'').slice(-6).toUpperCase())}</span><strong>${esc(o.customer?.name||o.name||'Kunde')}</strong><small>${esc(o.customer?.phone||o.phone||'')} · ${orderTime(o.createdAt)}</small></div><span class="order-status status-${esc(o.status||'mottatt')}">${esc(orderStatusLabel(o.status||'mottatt'))}</span></div><p>${esc(items||'Ingen varelinjer')}</p><div class="order-meta"><span>Henting: <b>${esc(o.pickupTime||o.pickup?.label||o.pickup||'—')}</b></span><span>Total: <b>${esc(o.total||0)} kr</b></span></div><div class="order-actions"><button class="ghost" data-order-id="${esc(o.id)}" data-order-status="tilberedning">Tilberedes</button><button class="ghost" data-order-id="${esc(o.id)}" data-order-status="klar">Klar</button><button class="ghost" data-order-id="${esc(o.id)}" data-order-status="hentet">Hentet</button></div></article>`}
async function setOrderStatus(id,statusValue){const orders=config.orders||{};if(Array.isArray(orders)){const o=orders.find(x=>x?.id===id);if(o)o.status=statusValue}else if(orders[id])orders[id].status=statusValue;try{await fetch(`${DB}/orders/${encodeURIComponent(id)}.json`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:statusValue,statusUpdatedAt:Date.now()})});toast('Ordre oppdatert');renderOrders()}catch(e){toast('Kunne ikke oppdatere ordre')}}
function showRestaurant(){mode='restaurant';setNav('restaurant');closeEditor();$('.page-head h1').textContent='Restaurant';$('.page-head p').textContent='Åpningstid, hentetid og restaurantinformasjon.';$('.tools').innerHTML='';$('#addCategoryBtn').hidden=true;renderRestaurant()}
function settingsObj(){config.siteSettings=config.siteSettings||config.settings||{};config.settings=config.siteSettings;return config.siteSettings}
function renderRestaurant(){if(mode!=='restaurant')return;const s=settingsObj();root.innerHTML=`<div class="restaurant-grid"><section class="restaurant-card"><h3>Restaurantinformasjon</h3><label>Navn<input id="rsName" value="${esc(s.restaurantName||'KØL Grill & Pizza')}" placeholder="Restaurantnavn"></label><label>Adresse<input id="rsAddress" value="${esc(s.streetAddress||'')}" placeholder="Gateadresse"></label><div class="restaurant-two"><label>Postnr.<input id="rsPostal" value="${esc(s.postalCode||'')}" placeholder="2100"></label><label>Sted<input id="rsCity" value="${esc(s.city||'SKARNES')}" placeholder="Skarnes"></label></div><label>Telefon<input id="rsPhone" value="${esc(s.phone||'')}" placeholder="+47 ..."></label></section><section class="restaurant-card"><h3>Bestilling & hentetid</h3><div class="restaurant-two"><label>Åpner<input id="rsOpen" type="time" value="${esc(s.orderOpenTime||'14:00')}"></label><label>Stenger<input id="rsClose" type="time" value="${esc(s.orderCloseTime||'22:00')}"></label></div><div class="restaurant-two"><label>Tilberedning (min)<input id="rsPrep" type="number" min="0" value="${Number(s.prepMinutes)||25}"></label><label>Intervall (min)<input id="rsInterval" type="number" min="5" value="${Number(s.slotIntervalMinutes)||15}"></label></div><label class="toggle-row"><div><strong>Steng nettbestilling manuelt</strong><small>Kunden kan se menyen, men ikke sende ordre.</small></div><span class="switch"><input id="rsClosed" type="checkbox" ${s.manualClosed?'checked':''}><i></i></span></label><label>Melding ved stengt<input id="rsClosedMsg" value="${esc(s.closedMessage||'Vi tar ikke imot bestillinger akkurat nå.')}" placeholder="Melding til kunden"></label></section></div>`;const map=[['rsName','restaurantName'],['rsAddress','streetAddress'],['rsPostal','postalCode'],['rsCity','city'],['rsPhone','phone'],['rsOpen','orderOpenTime'],['rsClose','orderCloseTime'],['rsPrep','prepMinutes'],['rsInterval','slotIntervalMinutes'],['rsClosedMsg','closedMessage']];map.forEach(([id,key])=>$('#'+id).oninput=e=>{s[key]=['prepMinutes','slotIntervalMinutes'].includes(key)?Number(e.target.value):e.target.value;markDirty()});$('#rsClosed').onchange=e=>{s.manualClosed=e.target.checked;markDirty()}}
'''
if 'function showOrders()' not in admin:
    admin=admin.replace('function filterItems(s){',extra+'\nfunction filterItems(s){')
admin=admin.replace("status.className='save-state saved';renderMenu();","status.className='save-state saved'; if(mode==='orders')renderOrders(); else if(mode==='restaurant')renderRestaurant(); else if(mode==='library')renderLibrary(); else renderMenu();")
admin=re.sub(r'kol\.css\?v=[^"\']+','kol.css?v=20260825-frontendv3',admin)
index=re.sub(r'kol\.css\?v=[^"\']+','kol.css?v=20260825-frontendv3',index)
(demo/'admin.html').write_text(admin,encoding='utf-8')
(demo/'index.html').write_text(index,encoding='utf-8')

start='/* ===== FRONTEND V3 REMIX ===== */'
if start in css: css=css.split(start)[0].rstrip()+'\n'
css += r'''
/* ===== FRONTEND V3 REMIX ===== */
:root{--v3-bg:#f4f5f6;--v3-surface:#fff;--v3-ink:#1c1f23;--v3-muted:#5b6470;--v3-line:#e3e5e8;--v3-accent:#e8620f;--v3-accent-dark:#c94f06;--v3-accent-soft:#fdf0e7;--v3-ok:#1f8a4c;--v3-sidebar:#1f2429}
body:not(.kol-customer){background:var(--v3-bg)!important;color:var(--v3-ink)!important;font-size:14px!important}
body:not(.kol-customer) .app{grid-template-columns:236px minmax(0,1fr) 0!important;height:100vh!important;overflow:hidden!important}
body:not(.kol-customer) .app.editor-open{grid-template-columns:236px minmax(0,1fr) 400px!important}
body:not(.kol-customer) .sidebar{background:var(--v3-sidebar)!important;color:#e7eaee!important;padding:14px 12px!important;border:0!important}
body:not(.kol-customer) .brand{padding:0 4px 14px!important;margin:0 0 12px!important;border-bottom:1px solid rgba(255,255,255,.1)!important}
body:not(.kol-customer) .brand-mark{width:30px!important;height:30px!important;border-radius:8px!important;background:var(--v3-accent)!important;font-size:13px!important}
body:not(.kol-customer) .brand strong{color:#fff!important;font-size:14px!important}body:not(.kol-customer) .brand small{color:#97a1ab!important;font-size:10px!important}
body:not(.kol-customer) .nav-title{color:#737e89!important;margin:14px 9px 6px!important}.nav-btn{border-radius:8px!important}
body:not(.kol-customer) .nav-btn{color:#c6ccd4!important;min-height:40px!important;padding:0 10px!important;margin:2px 0!important;font-size:13px!important}
body:not(.kol-customer) .nav-btn:hover{background:rgba(255,255,255,.07)!important;color:#fff!important;transform:none!important}
body:not(.kol-customer) .nav-btn.active{background:var(--v3-accent)!important;color:#fff!important;box-shadow:none!important}
body:not(.kol-customer) .nav-note{margin-top:auto!important;border-color:rgba(255,255,255,.1)!important;background:rgba(255,255,255,.04)!important;color:#8d97a2!important}
body:not(.kol-customer) .workspace{background:var(--v3-bg)!important;overflow:hidden!important}.topbar{height:56px!important}.content{height:calc(100vh - 56px)!important;overflow-y:scroll!important;padding:14px 16px 38px!important;scrollbar-width:auto!important;scrollbar-color:#9aa3ad #e9ecef!important}
body:not(.kol-customer) .content::-webkit-scrollbar,body:not(.kol-customer) .editor::-webkit-scrollbar{width:13px!important}.content::-webkit-scrollbar-track,.editor::-webkit-scrollbar-track{background:#e9ecef!important}.content::-webkit-scrollbar-thumb,.editor::-webkit-scrollbar-thumb{background:#9aa3ad!important;border:3px solid #e9ecef!important;border-radius:10px!important}
body:not(.kol-customer) .category-head,body:not(.kol-customer) .item,body:not(.kol-customer) .library-card{border-color:var(--v3-line)!important;border-radius:10px!important;box-shadow:0 1px 2px rgba(24,30,38,.06)!important}.editor{background:#f6f7f8!important;border-left:1px solid var(--v3-line)!important;overflow-y:scroll!important}.editor-card{border-color:var(--v3-line)!important;border-radius:10px!important}
.order-stats{display:grid;grid-template-columns:repeat(3,minmax(0,150px));gap:8px;margin-bottom:10px}.order-stats>div,.admin-order-card,.restaurant-card{background:#fff;border:1px solid var(--v3-line);border-radius:10px;padding:11px;box-shadow:0 1px 2px rgba(24,30,38,.05)}.order-stats b{display:block;font-size:20px}.order-stats span{font-size:10px;color:#8b939e}.admin-orders{display:grid;gap:8px}.order-card-top{display:flex;justify-content:space-between;gap:12px}.order-card-top strong,.order-card-top small{display:block}.order-card-top strong{font-size:13px}.order-card-top small,.order-number{font-size:10px;color:#8b939e}.order-status{padding:4px 8px;border-radius:999px;font-size:9px;font-weight:800;background:#eef1f3}.status-mottatt{background:#fdf0e7;color:#b64d0c}.status-tilberedning{background:#fff6d9;color:#8f6b00}.status-klar{background:#e8f6ec;color:#1f8a4c}.admin-order-card p{font-size:11px;color:#5b6470}.order-meta,.order-actions{display:flex;gap:8px}.order-meta{font-size:10px;color:#6f7882}.order-actions{margin-top:9px}.order-actions .ghost{height:32px;font-size:10px}.restaurant-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.restaurant-card h3{font-size:13px;margin:0 0 10px}.restaurant-card label{display:block;font-size:10px;font-weight:650;color:#65707b;margin-bottom:8px}.restaurant-card input{display:block;width:100%;height:38px;margin-top:4px;border:1px solid #d7dbe0;border-radius:8px;padding:0 9px}.restaurant-two{display:grid;grid-template-columns:1fr 1fr;gap:8px}
body.kol-customer{--head:52px!important;--tabs:44px!important;background:#f5f6f7!important;box-shadow:none!important}.customer-app{background:#f5f6f7!important}.appbar{background:#fff!important;color:#1c1f23!important;border-bottom:1px solid var(--v3-line)!important}.appbar-main{height:52px!important;padding:0 10px!important}.appbar-brand,.icon-button{color:#4f5964!important}.icon-button{border:0!important;background:transparent!important;width:40px!important;height:40px!important}.brand-logo b{font-size:18px!important;color:#1c1f23!important}.brand-logo small{color:#8b939e!important}.category-tabs-wrap{height:44px!important;background:#fff!important;border-bottom:1px solid var(--v3-line)!important}.category-tabs-scroll{gap:6px!important;padding:6px 10px!important;align-items:center!important}.category-tab,.search-tab{height:32px!important;border:1px solid var(--v3-line)!important;border-radius:16px!important;background:#fff!important;color:#5b6470!important;font-size:11px!important;padding:0 11px!important}.category-tab.active{background:var(--v3-accent)!important;border-color:var(--v3-accent)!important;color:#fff!important}.menu-shell{background:#f5f6f7!important;padding:10px!important}#menuSections{padding:0!important}.menu-section{border:0!important;margin-bottom:13px!important}.menu-row{background:#fff!important;border:1px solid var(--v3-line)!important;border-radius:12px!important;box-shadow:0 1px 2px rgba(24,30,38,.05)!important}.plus,.primary{background:var(--v3-accent)!important;border-color:var(--v3-accent)!important;color:#fff!important}.screen,.screen-scroll{background:#f5f6f7!important}.product-choice.active,.product-choice.selected{background:var(--v3-accent-soft)!important;color:#b64d0c!important}
@media(max-width:900px){.restaurant-grid{grid-template-columns:1fr}.order-stats{grid-template-columns:repeat(3,1fr)}}
'''
(demo/'kol.css').write_text(css,encoding='utf-8')
