from pathlib import Path

p = Path('test/test.html')
s = p.read_text(encoding='utf-8')

old_css = '''body.kol-customer .local-allergen-rail{flex:0 0 auto;height:48px;margin:0;padding:0 11px;display:inline-flex;align-items:center;justify-content:center;gap:6px;border:0;border-bottom:2px solid transparent;border-radius:0;background:#fff;color:#403a36;font-size:13px;font-weight:500;white-space:nowrap}\nbody.kol-customer .local-allergen-rail.has-filter{color:#f36a2d;border-bottom-color:#f36a2d}\nbody.kol-customer .local-more-wrap{padding:7px 12px 11px;border-bottom:1px solid var(--line);background:#fff}\nbody.kol-customer .local-more-button{width:100%;height:30px;margin:0;padding:0;border:1px solid #e4ded9;border-radius:4px;background:#fff;color:#625b56;font-size:12.5px;font-weight:500;box-shadow:none}\nbody.kol-customer .local-search-rail{width:100%;height:48px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:8px;padding:0 12px;background:#fff}\nbody.kol-customer .local-search-input-wrap{min-width:0;height:44px;display:flex;align-items:center;gap:9px}\nbody.kol-customer .local-search-input-wrap svg{flex:0 0 20px;width:20px;height:20px;fill:none;stroke:#171717;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}\nbody.kol-customer .local-search-input{width:100%;height:44px;margin:0;padding:0;border:0;outline:0;background:#fff;color:#171717;font-size:16px;box-shadow:none}\nbody.kol-customer .local-search-cancel{height:40px;margin:0;padding:0 2px 0 10px;border:0;background:transparent;color:#171717;font-size:15px;font-weight:500}\nbody.kol-customer .local-search-head{padding:16px 12px 12px;border-bottom:1px solid var(--line);background:#fff}\nbody.kol-customer .local-search-head-row{display:flex;align-items:center;justify-content:space-between;gap:10px}\nbody.kol-customer .local-search-head h2{margin:0;font-size:22px;font-weight:550;line-height:1.2}\nbody.kol-customer .local-search-meta{margin-top:8px;color:var(--muted);font-size:13px}\nbody.kol-customer .local-allergen-trigger{min-height:40px;padding:0 11px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid #dfd9d4;border-radius:10px;background:#fff;color:#2b2724;font-size:13px;font-weight:500;white-space:nowrap}'''
new_css = '''body.kol-customer .local-more-wrap{padding:7px 12px 11px;border-bottom:1px solid var(--line);background:#fff}\nbody.kol-customer .local-more-button{width:100%;height:30px;margin:0;padding:0;border:1px solid #e4ded9;border-radius:4px;background:#fff;color:#625b56;font-size:12.5px;font-weight:500;box-shadow:none}\nbody.kol-customer .local-search-rail{width:100%;height:48px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:10px;padding:0 12px;background:#fff;border:0}\nbody.kol-customer .local-search-input-wrap{min-width:0;height:48px;margin:0;padding:0;display:grid;grid-template-columns:28px minmax(0,1fr);align-items:center;gap:5px;border:0!important;border-radius:0!important;background:#fff!important;box-shadow:none!important}\nbody.kol-customer .local-search-input-wrap svg{width:21px;height:21px;fill:none;stroke:#171717;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}\nbody.kol-customer .local-search-input{width:100%!important;height:48px!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;outline:0!important;background:transparent!important;color:#171717!important;font-size:16px!important;box-shadow:none!important;-webkit-appearance:none!important;appearance:none!important}\nbody.kol-customer .local-search-input::-webkit-search-decoration,body.kol-customer .local-search-input::-webkit-search-cancel-button{-webkit-appearance:none}\nbody.kol-customer .local-search-cancel{height:48px;margin:0;padding:0 0 0 10px;border:0;border-radius:0;background:transparent;color:#171717;font-size:15px;font-weight:500;box-shadow:none}\nbody.kol-customer .local-menu-tools{min-height:64px;padding:8px 12px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid var(--line);background:#fff}\nbody.kol-customer .local-menu-tools h2{margin:0;color:#292522;font-size:22px;font-weight:550;line-height:1.2}\nbody.kol-customer .local-search-meta{padding:8px 12px;border-bottom:1px solid var(--line);color:var(--muted);font-size:13px;background:#fff}\nbody.kol-customer .local-allergen-trigger{min-height:44px;padding:0 14px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border:1px solid #e2ddd8;border-radius:13px;background:#fff;color:#403a36;font-size:14px;font-weight:500;white-space:nowrap;box-shadow:none}\nbody.kol-customer .local-allergen-trigger.has-filter{border-color:#f0b39a;color:#d95622;background:#fffaf7}\nbody.kol-customer .local-product-allergens{margin-top:2px;color:#c74336;font-size:11.5px;font-weight:400;line-height:1.25;white-space:normal}'''
assert old_css in s, 'old css block missing'
s = s.replace(old_css, new_css)

old_tabs = '''  els.tabs.innerHTML=`<button class="local-search-button" data-search-open type="button" aria-label="Søk"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m16.5 16.5 4 4"></path></svg></button><button class="local-allergen-rail ${selectedAllergens.size?'has-filter':''}" data-open-allergens type="button">⚠ Alergener${selectedAllergens.size?` <span class="local-allergen-count">${selectedAllergens.size}</span>`:''}</button>`+sectionsForRender().map((s,i)=>`<button class="category-tab ${i===0?'active':''}" data-tab="${s.id}" type="button">${s.title}</button>`).join('');'''
new_tabs = '''  els.tabs.innerHTML=`<button class="local-search-button" data-search-open type="button" aria-label="Søk"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m16.5 16.5 4 4"></path></svg></button>`+sectionsForRender().map((s,i)=>`<button class="category-tab ${i===0?'active':''}" data-tab="${s.id}" type="button">${s.title}</button>`).join('');'''
assert old_tabs in s, 'tabs block missing'
s = s.replace(old_tabs, new_tabs)

old_row = '''function productRow(p){return `<article class="menu-row menu-app-product" data-product="${p.id}">${p.image?`<span class="food-thumb custom-thumb" style="background-image:url('${p.image}')"></span>`:`<span class="food-thumb default-thumb"></span>`}<div class="menu-row-main"><div class="menu-row-headline"><strong>${p.name}</strong></div><div class="menu-row-description">${p.description||''}</div></div><div class="menu-app-product-side"><div class="menu-card-actions"><button class="menu-favorite local-fav ${favorites.has(p.id)?'saved':''}" data-fav="${p.id}" type="button" aria-label="Favoritt">${heart(favorites.has(p.id))}</button><button class="menu-app-plus local-plus" data-add="${p.id}" type="button" aria-label="Legg til">+</button></div><span class="menu-row-inline-price">${p.sizes.length>1?'Fra ':''}${money(basePrice(p))}</span></div></article>`}'''
new_row = '''function productAllergenText(p){if(!selectedAllergens.size)return '';const ids=allergensOf(p);if(!ids.length)return '';const labels=ids.map(id=>ALLERGENS.find(a=>a[0]===id)?.[2]||id);return `<div class="local-product-allergens">Inneholder: ${labels.join(', ')}</div>`}\nfunction productRow(p){return `<article class="menu-row menu-app-product" data-product="${p.id}">${p.image?`<span class="food-thumb custom-thumb" style="background-image:url('${p.image}')"></span>`:`<span class="food-thumb default-thumb"></span>`}<div class="menu-row-main"><div class="menu-row-headline"><strong>${p.name}</strong></div><div class="menu-row-description">${p.description||''}</div>${productAllergenText(p)}</div><div class="menu-app-product-side"><div class="menu-card-actions"><button class="menu-favorite local-fav ${favorites.has(p.id)?'saved':''}" data-fav="${p.id}" type="button" aria-label="Favoritt">${heart(favorites.has(p.id))}</button><button class="menu-app-plus local-plus" data-add="${p.id}" type="button" aria-label="Legg til">+</button></div><span class="menu-row-inline-price">${p.sizes.length>1?'Fra ':''}${money(basePrice(p))}</span></div></article>`}'''
assert old_row in s, 'product row missing'
s = s.replace(old_row, new_row)

old_render = '''  if(searchOpen){const items=sections[0]?.items||[];els.sections.innerHTML=`<div class="local-search-head"><div class="local-search-head-row"><h2>Søk i menyen</h2><button class="local-allergen-trigger" data-open-allergens type="button">⚠ Alergener ${selectedAllergens.size?`<span class="local-allergen-count">${selectedAllergens.size}</span>`:''}</button></div><div class="local-search-meta">${items.length} produkter funnet</div></div>${selectedAllergens.size?`<div class="local-filter-note">Skjuler produkter med: ${[...selectedAllergens].map(id=>ALLERGENS.find(a=>a[0]===id)?.[2]||id).join(', ')}</div>`:''}${items.length?`<section class="menu-app-section"><div class="menu-list">${items.map(productRow).join('')}</div></section>`:`<div class="local-empty-search">Ingen produkter passer søket eller allergenfilteret.</div>`}`;renderTabs();return}\n  els.sections.innerHTML=sections.map(s=>{const limited=s.id==='favorites'||s.id==='popular';const items=limited&&!expandedVirtual[s.id]?(s.items||[]).slice(0,3):(s.items||[]);const more=limited&&(s.items||[]).length>3?`<div class="local-more-wrap"><button class="local-more-button" data-vis-mer="${s.id}" type="button">${expandedVirtual[s.id]?'Vis mindre':'Vis mer'}</button></div>`:'';return `<section class="menu-app-section" data-section="${s.id}"><div class="menu-app-section-head"><h2>${s.title}</h2>${s.note?`<p>${s.note}</p>`:''}</div><div class="menu-list">${items.map(productRow).join('')}</div>${more}</section>`}).join('');renderTabs();'''
new_render = '''  const allergenButton=`<button class="local-allergen-trigger ${selectedAllergens.size?'has-filter':''}" data-open-allergens type="button"><span aria-hidden="true">⚠</span> Matallergier${selectedAllergens.size?` <span class="local-allergen-count">${selectedAllergens.size}</span>`:''}</button>`;\n  const tools=`<div class="local-menu-tools"><h2>Meny</h2>${allergenButton}</div>`;\n  if(searchOpen){const items=sections[0]?.items||[];els.sections.innerHTML=`${tools}<div class="local-search-meta">${items.length} produkter funnet</div>${selectedAllergens.size?`<div class="local-filter-note">Skjuler produkter med: ${[...selectedAllergens].map(id=>ALLERGENS.find(a=>a[0]===id)?.[2]||id).join(', ')}</div>`:''}${items.length?`<section class="menu-app-section"><div class="menu-list">${items.map(productRow).join('')}</div></section>`:`<div class="local-empty-search">Ingen produkter passer søket eller allergenfilteret.</div>`}`;renderTabs();return}\n  els.sections.innerHTML=tools+(selectedAllergens.size?`<div class="local-filter-note">Skjuler produkter med: ${[...selectedAllergens].map(id=>ALLERGENS.find(a=>a[0]===id)?.[2]||id).join(', ')}</div>`:'')+sections.map(s=>{const limited=s.id==='favorites'||s.id==='popular';const items=limited&&!expandedVirtual[s.id]?(s.items||[]).slice(0,3):(s.items||[]);const more=limited&&(s.items||[]).length>3?`<div class="local-more-wrap"><button class="local-more-button" data-vis-mer="${s.id}" type="button">${expandedVirtual[s.id]?'Vis mindre':'Vis mer'}</button></div>`:'';return `<section class="menu-app-section" data-section="${s.id}"><div class="menu-app-section-head"><h2>${s.title}</h2>${s.note?`<p>${s.note}</p>`:''}</div><div class="menu-list">${items.map(productRow).join('')}</div>${more}</section>`}).join('');renderTabs();'''
assert old_render in s, 'render block missing'
s = s.replace(old_render, new_render)

p.write_text(s, encoding='utf-8')
print('patched test/test.html')
