(()=>{
'use strict';
const DB='https://bestill-19-default-rtdb.europe-west1.firebasedatabase.app';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const arr=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const ALLERGENS=[['melk','Melk'],['gluten','Gluten'],['egg','Egg'],['soya','Soya'],['selleri','Selleri'],['sennep','Sennep'],['sesam','Sesam'],['fisk','Fisk'],['skalldyr','Skalldyr'],['peanøtter','Peanøtter'],['nøtter','Nøtter'],['sulfitter','Sulfitter']];
let config={sections:[],optionGroups:[]}, openSection='', editing=null, search='', dirty=false, saveTimer=0, saving=false, dragData=null, mode='menu';
const root=$('#menuRoot'), status=$('#saveState'), saveBtn=$('#saveBtn');
const uid=(p='id')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;

injectPolish();
injectLibraryNav();

function injectPolish(){
 const s=document.createElement('style');
 s.textContent=`
 html,body{scrollbar-width:auto;scrollbar-color:#9d958f #ece8e5}
 ::-webkit-scrollbar{width:14px;height:14px}::-webkit-scrollbar-track{background:#ece8e5}::-webkit-scrollbar-thumb{background:#9d958f;border:3px solid #ece8e5;border-radius:10px}::-webkit-scrollbar-thumb:hover{background:#746c67}
 .content{max-width:none!important;width:100%!important;margin:0!important;padding:18px 20px 42px!important}
 .app{grid-template-columns:190px minmax(0,1fr) 0!important}.app.editor-open{grid-template-columns:190px minmax(0,1fr) 420px!important}
 .sidebar{padding:18px 12px!important}.brand{margin-bottom:18px!important}.nav-note{margin-top:12px!important;padding-top:12px!important}
 .topbar{height:58px!important;padding:0 18px!important}.page-head{margin-bottom:12px!important;align-items:center!important}.page-head h1{font-size:22px!important}.page-head p{margin-top:3px!important}
 .category{margin-bottom:8px!important}.category-head{min-height:68px!important;padding:8px 10px!important;grid-template-columns:22px 46px minmax(0,1fr) auto!important}.cat-image{width:44px!important;height:44px!important}.category-body{margin:6px 0 0 16px!important}
 .item{min-height:64px!important;padding:6px 8px!important;margin-bottom:5px!important;grid-template-columns:16px 44px minmax(0,1fr) 78px 126px!important}.item-img{width:42px!important;height:42px!important}
 .editor{overflow-y:scroll!important;scrollbar-gutter:stable;height:100vh!important}.editor-body{padding:8px!important}.editor-head{height:58px!important;padding:0 12px!important}.editor-card{margin-bottom:7px!important}.editor-card-head{height:40px!important;padding:0 10px!important}.editor-card-body{padding:9px!important}
 .field{margin-bottom:7px!important}.field textarea{min-height:58px!important}.chips{gap:4px!important}.chip-check{min-height:30px!important}
 .library-list{display:grid;gap:8px}.library-card{background:#fff;border:1px solid var(--line);border-radius:11px;box-shadow:var(--shadow);padding:12px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center}.library-card h3{margin:0 0 5px;font-size:13px}.library-card p{margin:0;color:var(--muted);font-size:10.5px}.library-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.library-actions{display:flex;gap:5px}.lib-badge{padding:3px 7px;border-radius:999px;background:#f3f0ee;font-size:9px;color:#6d655f}.lib-badge.orange{background:#fff0e8;color:#c55629}.library-empty{background:#fff;border:1px dashed #d5ccc6;border-radius:12px;padding:32px;text-align:center;color:#8c837d}.library-toolbar{display:flex;gap:8px;align-items:center}.library-toolbar button{height:38px;border-radius:8px;padding:0 12px;font-weight:700}.attach-list{display:grid;gap:6px}.attach-row{border:1px solid #e5dfda;border-radius:9px;padding:9px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;background:#fff}.attach-row strong{display:block;font-size:11px}.attach-row small{display:block;margin-top:3px;color:#8d847e;font-size:9px}.attached-group{border:1px solid #e7dfda;border-radius:9px;padding:9px;margin-bottom:6px;background:#fff}.attached-group-head{display:flex;align-items:center;gap:8px}.attached-group-head>div{min-width:0;flex:1}.attached-group strong{display:block;font-size:11px}.attached-group small{display:block;color:#8d847e;font-size:9px;margin-top:3px}.attached-group-actions{display:flex;gap:4px}.modal-backdrop{position:fixed;inset:0;z-index:200;background:rgba(30,24,20,.38);display:grid;place-items:center;padding:20px}.modal-card{width:min(520px,100%);max-height:78vh;overflow-y:auto;background:#f8f7f5;border-radius:14px;box-shadow:0 18px 60px #0004;border:1px solid #ddd5d0}.modal-head{position:sticky;top:0;background:#fff;border-bottom:1px solid #e8e2de;padding:12px 14px;display:flex;align-items:center;z-index:2}.modal-head h3{font-size:14px;margin:0}.modal-head button{margin-left:auto;border:0;background:transparent;font-size:22px}.modal-body{padding:10px}.modal-foot{position:sticky;bottom:0;padding:10px;background:#fff;border-top:1px solid #e8e2de}.group-editor-title{display:grid;grid-template-columns:minmax(0,1fr);gap:6px}.group-editor-title input{height:38px;border:1px solid #d8d1cc;border-radius:8px;padding:0 10px}.choice-head,.choice-row{grid-template-columns:26px minmax(0,1fr) 78px 28px!important}.shared-warning{padding:8px 9px;border-radius:8px;background:#fff6e9;color:#895d20;font-size:9.5px;line-height:1.4;margin-bottom:8px}
 @media(max-width:980px){.app,.app.editor-open{grid-template-columns:170px minmax(0,1fr)!important}.editor{position:fixed!important;right:0!important;top:0!important;width:min(430px,92vw)!important;box-shadow:-10px 0 30px #0002}.content{padding:14px!important}}
 `;
 document.head.appendChild(s);
}
function injectLibraryNav(){
 const navs=$$('.sidebar .nav-btn');
 if(!navs.length)return;
 navs[0].id='navProducts';
 const b=document.createElement('button');b.className='nav-btn';b.id='navChoices';b.innerHTML='⊕ &nbsp; Choices & addons';
 navs[0].after(b);
 b.onclick=()=>showLibrary();
 navs[0].onclick=()=>showMenu();
}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function normalize(){
 config.sections=arr(config.sections).map(s=>({...s,id:String(s?.id||uid('section')),items:arr(s?.items)}));
 config.sections.forEach(s=>s.items=s.items.map(p=>{const sizes=arr(p?.sizes).map(x=>({id:String(x?.id||uid('size')),label:String(x?.label||x?.name||''),price:Number(x?.price)||0}));return {...p,id:String(p?.id||uid('product')),sizes:sizes.length?sizes:[{id:uid('size'),label:'Standard',price:Number(p?.price??p?.mediumPrice)||0}],defaultSizeIndex:Math.min(Math.max(0,Number(p?.defaultSizeIndex)||0),Math.max(0,sizes.length-1)),optionGroupIds:arr(p?.optionGroupIds).map(String),allergens:arr(p?.allergens)};}));
 config.optionGroups=arr(config.optionGroups).map(g=>({...g,id:String(g?.id||uid('group')),title:String(g?.title||''),selectionMode:g?.selectionMode==='multiple'?'multiple':'single',required:Boolean(g?.required),maxSelections:Math.max(1,Number(g?.maxSelections)||1),defaultOptionIds:arr(g?.defaultOptionIds).map(String),options:arr(g?.options).map(o=>({id:String(o?.id||uid('option')),label:String(o?.label||''),price:Number(o?.price)||0}))}));
}
async function load(){try{const r=await fetch(DB+'/.json',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);config=await r.json()||{};normalize();status.textContent='Kaydedildi';status.className='save-state saved';renderMenu();}catch(e){root.innerHTML=`<div class="empty">Menü yüklenemedi: ${esc(e.message)}</div>`;status.textContent='Hata';status.className='save-state error'}}
function markDirty(){dirty=true;status.textContent='Değişiklik var';status.className='save-state dirty';saveBtn.disabled=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(false),900)}
async function save(manual=true){if(saving||!dirty)return;saving=true;clearTimeout(saveTimer);status.textContent='Kaydediliyor…';status.className='save-state saving';saveBtn.disabled=true;try{const r=await fetch(DB+'/.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});if(!r.ok)throw Error('HTTP '+r.status);dirty=false;status.textContent='Kaydedildi';status.className='save-state saved';if(manual)toast('Değişiklikler kaydedildi')}catch(e){dirty=true;status.textContent='Kaydetme hatası';status.className='save-state error';saveBtn.disabled=false;toast('Kaydedilemedi')}finally{saving=false}}
function pimg(p){return p.imageUrl||p.image||''}function simg(s){return s.imageUrl||s.image||s.items.map(pimg).find(Boolean)||''}function priceText(p){const v=p.sizes.map(x=>Number(x.price)).filter(Number.isFinite);if(!v.length)return'';const mn=Math.min(...v),mx=Math.max(...v);return mn===mx?`${mn} kr`:`fra ${mn} kr`}function usageCount(id){let n=0;config.sections.forEach(s=>s.items.forEach(p=>{if(p.optionGroupIds.includes(id))n++}));return n}
function setNav(which){$('#navProducts')?.classList.toggle('active',which==='menu');$('#navChoices')?.classList.toggle('active',which==='library')}
function showMenu(){mode='menu';setNav('menu');closeEditor();$('.page-head h1').textContent='Meny';$('.page-head p').textContent='Kategorier, produkter, priser, tilgjengelighet og valg.';$('.tools').innerHTML='<input class="search" id="menuSearch" placeholder="Søk etter produkt"><button class="ghost" id="collapseBtn">Lukk kategori</button>';$('#addCategoryBtn').hidden=false;bindTopTools();renderMenu()}
function showLibrary(){mode='library';setNav('library');closeEditor();$('.page-head h1').textContent='Choices & addons';$('.page-head p').textContent='Lag valggrupper én gang og bruk dem på så mange produkter du vil.';$('.tools').innerHTML='<button class="ghost" id="newLibraryGroup">+ Ny valggruppe</button>';$('#addCategoryBtn').hidden=true;$('#newLibraryGroup').onclick=()=>createLibraryGroup();renderLibrary()}
function filterItems(s){if(!search)return s.items;const q=search.toLocaleLowerCase('nb-NO');return s.items.filter(p=>`${p.name||''} ${p.description||p.ingredients||''}`.toLocaleLowerCase('nb-NO').includes(q))}
function renderMenu(){if(mode!=='menu')return;root.innerHTML=config.sections.map((s,si)=>sectionHtml(s,si)).join('')||'<div class="empty">Ingen kategorier</div>';bindList()}
function sectionHtml(s,si){const open=search?filterItems(s).length>0:openSection===s.id;if(search&&!filterItems(s).length)return'';const img=simg(s);return `<section class="category" draggable="true" data-si="${si}"><div class="category-head"><span class="cat-drag">⋮⋮</span><div class="cat-image" ${img?`style="background-image:url('${esc(img)}')"`:''}></div><div class="cat-copy"><strong>${esc(s.title||'Ny kategori')}</strong><small>${esc(s.note||s.description||'Klikk for å åpne')}</small></div><div class="cat-meta"><span class="count">${s.items.length} produkter</span><button class="icon-btn cat-edit" title="Rediger">✎</button><span>${open?'⌃':'⌄'}</span></div></div><div class="category-body" ${open?'':'hidden'}>${filterItems(s).map(p=>itemHtml(p,si,s.items.indexOf(p))).join('')}<button class="add-item" data-add-product="${si}">+ Legg til produkt</button></div></section>`}
function itemHtml(p,si,pi){const def=p.sizes[Math.min(p.defaultSizeIndex,p.sizes.length-1)],groups=p.optionGroupIds.length,img=pimg(p);return `<article class="item" draggable="true" data-si="${si}" data-pi="${pi}"><span class="drag">≡</span><div class="item-img" ${img?`style="background-image:url('${esc(img)}')"`:''}></div><div class="item-copy"><div class="badges">${def?`<span class="badge green">Standard: ${esc(def.label||'Standard')}</span>`:''}${groups?`<span class="badge orange">${groups} valggruppe${groups>1?'r':''}</span>`:''}${p.hidden?'<span class="badge gray">Skjult</span>':''}${p.soldOut?'<span class="badge red">Utsolgt</span>':''}</div><strong>${esc(p.name||'Nytt produkt')}</strong><small>${esc(p.description||p.ingredients||'')}</small></div><div class="item-price">${esc(priceText(p))}</div><div class="item-actions"><button class="mini-action add-group-direct">+ Valg</button><button class="icon-btn item-edit">✎</button><button class="icon-btn item-more">⋯</button></div></article>`}
function bindList(){
 $$('.category-head').forEach(h=>h.onclick=e=>{if(e.target.closest('button,.cat-drag'))return;const si=+h.closest('.category').dataset.si;openSection=openSection===config.sections[si].id?'':config.sections[si].id;renderMenu()});
 $$('.cat-edit').forEach(b=>b.onclick=e=>{e.stopPropagation();editCategory(+b.closest('.category').dataset.si)});$$('.item-edit').forEach(b=>b.onclick=()=>{const a=b.closest('.item');editProduct(+a.dataset.si,+a.dataset.pi)});$$('.add-group-direct').forEach(b=>b.onclick=()=>{const a=b.closest('.item');openGroupPicker(+a.dataset.si,+a.dataset.pi)});$$('[data-add-product]').forEach(b=>b.onclick=()=>addProduct(+b.dataset.addProduct));$$('.item-more').forEach(b=>b.onclick=()=>{const a=b.closest('.item'),si=+a.dataset.si,pi=+a.dataset.pi,p=config.sections[si].items[pi];if(confirm(`Dupliser ${p.name||'produkt'}?`)){const c=structuredClone(p);c.id=uid('product');c.name=(c.name||'Produkt')+' – kopi';config.sections[si].items.splice(pi+1,0,c);markDirty();renderMenu()}});bindDrag();
}
function bindDrag(){
 $$('.category').forEach(cat=>{cat.ondragstart=e=>{if(!e.target.closest('.cat-drag')&&e.target!==cat){e.preventDefault();return}dragData={type:'cat',si:+cat.dataset.si};cat.classList.add('dragging')};cat.ondragend=()=>cat.classList.remove('dragging');cat.ondragover=e=>{if(dragData?.type==='cat'){e.preventDefault();cat.classList.add('drag-over')}};cat.ondragleave=()=>cat.classList.remove('drag-over');cat.ondrop=()=>{cat.classList.remove('drag-over');if(dragData?.type!=='cat')return;const to=+cat.dataset.si,from=dragData.si;if(from!==to){const[m]=config.sections.splice(from,1);config.sections.splice(to,0,m);markDirty();renderMenu()}}});
 $$('.item').forEach(item=>{item.ondragstart=e=>{if(!e.target.closest('.drag')&&e.target!==item){e.preventDefault();return}dragData={type:'item',si:+item.dataset.si,pi:+item.dataset.pi};item.classList.add('dragging')};item.ondragend=()=>item.classList.remove('dragging');item.ondragover=e=>{if(dragData?.type==='item'){e.preventDefault();item.classList.add('drag-over')}};item.ondragleave=()=>item.classList.remove('drag-over');item.ondrop=()=>{item.classList.remove('drag-over');if(dragData?.type!=='item')return;const tsi=+item.dataset.si,tpi=+item.dataset.pi,{si:fsi,pi:fpi}=dragData;const[m]=config.sections[fsi].items.splice(fpi,1);config.sections[tsi].items.splice(tpi,0,m);markDirty();renderMenu()}});
 $$('.category-body').forEach(body=>{body.ondragover=e=>{if(dragData?.type==='item')e.preventDefault()};body.ondrop=e=>{if(dragData?.type!=='item'||e.target.closest('.item'))return;const tsi=+body.closest('.category').dataset.si,{si:fsi,pi:fpi}=dragData;const[m]=config.sections[fsi].items.splice(fpi,1);config.sections[tsi].items.push(m);markDirty();renderMenu()}})
}
function renderLibrary(){if(mode!=='library')return;root.innerHTML=config.optionGroups.length?`<div class="library-list">${config.optionGroups.map((g,i)=>libraryCard(g,i)).join('')}</div>`:`<div class="library-empty"><strong>Ingen valggrupper ennå</strong><p>Lag f.eks. «Velg saus», «Styrke» eller «Ekstra topping» én gang, og koble den til flere produkter.</p><button class="ghost" id="emptyNewGroup">+ Ny valggruppe</button></div>`;$$('[data-edit-group]').forEach(b=>b.onclick=()=>editLibraryGroup(+b.dataset.editGroup));$$('[data-dup-group]').forEach(b=>b.onclick=()=>duplicateGroup(+b.dataset.dupGroup));$('#emptyNewGroup')?.addEventListener('click',()=>createLibraryGroup())}
function libraryCard(g,i){const used=usageCount(g.id),modeText=g.selectionMode==='multiple'?`Flere valg · maks ${g.maxSelections}`:'Ett valg';return `<div class="library-card"><div><h3>${esc(g.title||'Uten navn')}</h3><p>${g.options.length} alternativer · ${modeText}${g.required?' · obligatorisk':''}</p><div class="library-tags"><span class="lib-badge orange">Brukes på ${used} produkt${used===1?'':'er'}</span>${g.defaultOptionIds.length?`<span class="lib-badge">${g.defaultOptionIds.length} standardvalg</span>`:''}</div></div><div class="library-actions"><button class="ghost" data-edit-group="${i}">Rediger</button><button class="icon-btn" data-dup-group="${i}" title="Dupliser">⧉</button></div></div>`}
function openEditor(title,sub='PRODUKTINNSTILLINGER'){editing=editing||{};$('#app').classList.add('editor-open');$('#editorTitle').textContent=title;$('#editorEyebrow').textContent=sub}function closeEditor(){editing=null;$('#app').classList.remove('editor-open');$('#editorBody').innerHTML=''}function card(title,body,sub=''){return `<section class="editor-card"><div class="editor-card-head"><h4>${esc(title)}</h4>${sub?`<small>${esc(sub)}</small>`:''}</div><div class="editor-card-body">${body}</div></section>`}
function editCategory(si){const s=config.sections[si];editing={type:'category',si};openEditor('Kategoriinnstillinger','KATEGORI');$('#editorBody').innerHTML=card('Kategori',`<label class="field"><span>Navn</span><input id="catTitle" placeholder="F.eks. Pizza" value="${esc(s.title||'')}"></label><label class="field"><span>Beskrivelse</span><textarea id="catNote" placeholder="Kort beskrivelse">${esc(s.note||s.description||'')}</textarea></label><label class="field"><span>Bilde-URL</span><input id="catImage" placeholder="https://…" value="${esc(s.imageUrl||'')}"></label>`)+card('Handlinger',`<button class="danger-wide" id="deleteCat">Slett kategori</button>`);$('#catTitle').oninput=e=>{s.title=e.target.value;markDirty();renderMenu()};$('#catNote').oninput=e=>{s.note=e.target.value;markDirty();renderMenu()};$('#catImage').oninput=e=>{s.imageUrl=e.target.value;markDirty();renderMenu()};$('#deleteCat').onclick=()=>{if(confirm('Slette kategorien og alle produktene?')){config.sections.splice(si,1);markDirty();closeEditor();renderMenu()}}}
function addProduct(si){const p={id:uid('product'),name:'',description:'',imageUrl:'',sizes:[{id:uid('size'),label:'',price:0}],defaultSizeIndex:0,allergens:[],optionGroupIds:[],hidden:false,soldOut:false};config.sections[si].items.push(p);openSection=config.sections[si].id;markDirty();renderMenu();editProduct(si,config.sections[si].items.length-1)}
function editProduct(si,pi){editing={type:'product',si,pi};openEditor(config.sections[si].items[pi].name||'Nytt produkt');renderProductEditor()}
function renderProductEditor(){const{si,pi}=editing,p=config.sections[si].items[pi];$('#editorBody').innerHTML=card('Grunninformasjon',`<label class="field"><span>Produktnavn</span><input id="pName" placeholder="F.eks. 3 - Al Capone" value="${esc(p.name||'')}"></label><label class="field"><span>Beskrivelse</span><textarea id="pDesc" placeholder="Ingredienser og kort beskrivelse">${esc(p.description||p.ingredients||'')}</textarea></label><label class="field"><span>Bilde-URL</span><input id="pImage" placeholder="https://…" value="${esc(p.imageUrl||p.image||'')}"></label>`)+card('Størrelser og priser',`<div class="size-head"><span>Valgt</span><span>Størrelse</span><span>Pris</span><span></span></div><div id="sizeRows">${p.sizes.map((s,i)=>sizeRow(s,i,p.defaultSizeIndex)).join('')}</div><button class="add-line" id="addSize">+ Legg til størrelse</button><p class="hint">Den markerte størrelsen er valgt når kunden åpner produktet.</p>`,'Velg standard')+card('Allergener',`<div class="chips">${ALLERGENS.map(([id,l])=>`<label class="chip-check"><input type="checkbox" data-allergen="${id}" ${p.allergens.includes(id)?'checked':''}>${l}</label>`).join('')}</div>`)+card('Choices & addons',`${attachedGroupsHtml(p)}<button class="primary-line" id="attachGroup">+ Legg til valggruppe</button><p class="hint">Velg fra biblioteket. Du trenger ikke skrive samme valg på nytt for hvert produkt.</p>`,'Delte valggrupper')+card('Tilgjengelighet',`<label class="toggle-row"><span><strong>Vis produktet</strong><small>Skjul uten å slette</small></span><span class="switch"><input id="visible" type="checkbox" ${p.hidden?'':'checked'}><i></i></span></label><label class="toggle-row"><span><strong>Utsolgt</strong><small>Kunden kan ikke bestille</small></span><span class="switch"><input id="sold" type="checkbox" ${p.soldOut?'checked':''}><i></i></span></label>`)+card('Mer',`<button class="quiet" id="duplicate">Dupliser produkt</button> <button class="danger-wide" id="deleteProduct">Slett produkt</button>`);bindProductEditor()}
function attachedGroupsHtml(p){const linked=config.optionGroups.filter(g=>p.optionGroupIds.includes(g.id));if(!linked.length)return'<p class="hint">Ingen valggrupper er koblet til dette produktet.</p>';return linked.map(g=>`<div class="attached-group" data-gid="${esc(g.id)}"><div class="attached-group-head"><div><strong>${esc(g.title||'Uten navn')}</strong><small>${g.options.length} alternativer · ${g.selectionMode==='multiple'?'Flere valg':'Ett valg'}</small></div><div class="attached-group-actions"><button class="quiet edit-attached">Rediger</button><button class="remove-mini unlink-attached">×</button></div></div></div>`).join('')}
function sizeRow(s,i,d){return `<div class="size-row" data-i="${i}"><label><input type="radio" name="defsize" ${i===d?'checked':''}></label><input class="sl" placeholder="F.eks. Stor" value="${esc(s.label||'')}"><input class="sp" type="number" min="0" placeholder="0" value="${Number(s.price)||''}"><button class="remove-mini sr">×</button></div>`}
function bindProductEditor(){const{si,pi}=editing,p=config.sections[si].items[pi];$('#pName').oninput=e=>{p.name=e.target.value;$('#editorTitle').textContent=p.name||'Nytt produkt';markDirty();renderMenu()};$('#pDesc').oninput=e=>{p.description=e.target.value;delete p.ingredients;markDirty();renderMenu()};$('#pImage').oninput=e=>{p.imageUrl=e.target.value;delete p.image;markDirty();renderMenu()};$$('.size-row').forEach(r=>{const i=+r.dataset.i;r.querySelector('input[type=radio]').onchange=()=>{p.defaultSizeIndex=i;markDirty();renderMenu()};r.querySelector('.sl').oninput=e=>{p.sizes[i].label=e.target.value;markDirty();renderMenu()};r.querySelector('.sp').oninput=e=>{p.sizes[i].price=Number(e.target.value)||0;markDirty();renderMenu()};r.querySelector('.sr').onclick=()=>{if(p.sizes.length===1)return toast('Minst én størrelse må være');p.sizes.splice(i,1);p.defaultSizeIndex=Math.min(p.defaultSizeIndex,p.sizes.length-1);markDirty();renderProductEditor();renderMenu()}});$('#addSize').onclick=()=>{p.sizes.push({id:uid('size'),label:'',price:0});markDirty();renderProductEditor()};$$('[data-allergen]').forEach(c=>c.onchange=e=>{const set=new Set(p.allergens);e.target.checked?set.add(e.target.dataset.allergen):set.delete(e.target.dataset.allergen);p.allergens=[...set];markDirty()});$('#visible').onchange=e=>{p.hidden=!e.target.checked;markDirty();renderMenu()};$('#sold').onchange=e=>{p.soldOut=e.target.checked;markDirty();renderMenu()};$('#attachGroup').onclick=()=>openGroupPicker(si,pi);$$('.unlink-attached').forEach(b=>b.onclick=()=>{const gid=b.closest('.attached-group').dataset.gid;p.optionGroupIds=p.optionGroupIds.filter(id=>id!==gid);markDirty();renderProductEditor();renderMenu()});$$('.edit-attached').forEach(b=>b.onclick=()=>{const gid=b.closest('.attached-group').dataset.gid;const gi=config.optionGroups.findIndex(g=>g.id===gid);if(gi>=0)editLibraryGroup(gi,{returnTo:{si,pi}})});$('#duplicate').onclick=()=>{const c=structuredClone(p);c.id=uid('product');c.name=(c.name||'Produkt')+' – kopi';config.sections[si].items.splice(pi+1,0,c);markDirty();renderMenu();toast('Produkt duplisert')};$('#deleteProduct').onclick=()=>{if(confirm('Slette produktet?')){config.sections[si].items.splice(pi,1);markDirty();closeEditor();renderMenu()}}}
function openGroupPicker(si,pi){const p=config.sections[si].items[pi],available=config.optionGroups.filter(g=>!p.optionGroupIds.includes(g.id));const overlay=document.createElement('div');overlay.className='modal-backdrop';overlay.innerHTML=`<div class="modal-card"><div class="modal-head"><h3>Legg til valggruppe</h3><button class="modal-close">×</button></div><div class="modal-body">${available.length?`<div class="attach-list">${available.map(g=>`<div class="attach-row"><div><strong>${esc(g.title||'Uten navn')}</strong><small>${g.options.length} alternativer · brukes på ${usageCount(g.id)} produkt${usageCount(g.id)===1?'':'er'}</small></div><button class="ghost attach-existing" data-gid="${esc(g.id)}">Legg til</button></div>`).join('')}</div>`:'<div class="library-empty">Alle eksisterende valggrupper er allerede koblet til produktet.</div>'}</div><div class="modal-foot"><button class="primary-line create-and-attach">+ Lag ny valggruppe</button></div></div>`;document.body.appendChild(overlay);overlay.querySelector('.modal-close').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()};overlay.querySelectorAll('.attach-existing').forEach(b=>b.onclick=()=>{p.optionGroupIds.push(b.dataset.gid);markDirty();overlay.remove();renderMenu();if(editing?.type==='product'&&editing.si===si&&editing.pi===pi)renderProductEditor();toast('Valggruppe lagt til')});overlay.querySelector('.create-and-attach').onclick=()=>{const g=newGroup();config.optionGroups.push(g);p.optionGroupIds.push(g.id);markDirty();overlay.remove();editLibraryGroup(config.optionGroups.length-1,{returnTo:{si,pi}})}}
function newGroup(){return{id:uid('group'),title:'',selectionMode:'single',required:false,maxSelections:1,defaultOptionIds:[],options:[{id:uid('option'),label:'',price:0}]}}
function createLibraryGroup(){const g=newGroup();config.optionGroups.push(g);markDirty();editLibraryGroup(config.optionGroups.length-1)}
function duplicateGroup(i){const g=structuredClone(config.optionGroups[i]);g.id=uid('group');g.title=(g.title||'Valggruppe')+' – kopi';g.options=g.options.map(o=>({...o,id:uid('option')}));g.defaultOptionIds=[];config.optionGroups.splice(i+1,0,g);markDirty();renderLibrary();toast('Valggruppe duplisert')}
function editLibraryGroup(i,opts={}){const g=config.optionGroups[i];if(!g)return;editing={type:'group',gi:i,returnTo:opts.returnTo||null};openEditor(g.title||'Ny valggruppe','CHOICES & ADDONS');renderGroupEditor()}
function renderGroupEditor(){const{gi}=editing,g=config.optionGroups[gi],used=usageCount(g.id);$('#editorBody').innerHTML=(used?`<div class="shared-warning">Denne valggruppen brukes på <b>${used}</b> produkt${used===1?'':'er'}. Endringer her oppdaterer alle produktene som bruker gruppen.</div>`:'')+card('Valggruppe',`<div class="group-editor-title"><input id="gTitle" placeholder="F.eks. Velg saus" value="${esc(g.title||'')}"></div><div class="choice-mode" style="margin-top:8px"><button id="modeSingle" class="${g.selectionMode==='single'?'active':''}">○ Ett valg</button><button id="modeMultiple" class="${g.selectionMode==='multiple'?'active':''}">☑ Flere valg</button></div><p class="group-help">${g.selectionMode==='single'?'Kunden kan velge ett alternativ.':'Kunden kan velge flere alternativer.'}</p><div class="choice-head"><span>Start</span><span>Alternativ</span><span>+ pris</span><span></span></div><div id="choiceRows">${g.options.map((o,oi)=>choiceRow(g,o,oi)).join('')}</div><button class="add-line" id="addChoice">+ Legg til alternativ</button><div class="rule-box"><label class="toggle-row"><span><strong>Obligatorisk valg</strong><small>Kunden må velge før produktet kan legges i kurven</small></span><span class="switch"><input id="required" type="checkbox" ${g.required?'checked':''}><i></i></span></label>${g.selectionMode==='multiple'?`<label class="field" style="margin-top:8px"><span>Maks antall kunden kan velge</span><input id="maxSel" type="number" min="1" value="${g.maxSelections}"></label>`:''}</div><button class="danger-link" id="deleteGroup">Slett valggruppen helt</button>`)+card('Bruk',`<p class="hint">Koble gruppen til produkter med <b>+ Valg</b> i menyen. Du kan bruke samme gruppe på så mange produkter du vil.</p>`);bindGroupEditor()}
function choiceRow(g,o,oi){const checked=g.defaultOptionIds.includes(o.id),type=g.selectionMode==='multiple'?'checkbox':'radio';return `<div class="choice-row" data-oi="${oi}"><label><input class="choice-def" type="${type}" name="groupDefault" ${checked?'checked':''}></label><input class="choice-label" placeholder="F.eks. Mild" value="${esc(o.label||'')}"><input class="choice-price" type="number" min="0" placeholder="0" value="${Number(o.price)||''}"><button class="remove-mini choice-remove">×</button></div>`}
function bindGroupEditor(){const{gi}=editing,g=config.optionGroups[gi];$('#gTitle').oninput=e=>{g.title=e.target.value;$('#editorTitle').textContent=g.title||'Ny valggruppe';markDirty();if(mode==='library')renderLibrary()};$('#modeSingle').onclick=()=>{g.selectionMode='single';g.maxSelections=1;if(g.defaultOptionIds.length>1)g.defaultOptionIds=g.defaultOptionIds.slice(0,1);markDirty();renderGroupEditor()};$('#modeMultiple').onclick=()=>{g.selectionMode='multiple';g.maxSelections=Math.max(1,g.maxSelections||1);markDirty();renderGroupEditor()};$$('.choice-row').forEach(r=>{const oi=+r.dataset.oi,o=g.options[oi];r.querySelector('.choice-label').oninput=e=>{o.label=e.target.value;markDirty()};r.querySelector('.choice-price').oninput=e=>{o.price=Number(e.target.value)||0;markDirty()};r.querySelector('.choice-def').onchange=e=>{if(g.selectionMode==='single'){g.defaultOptionIds=e.target.checked?[o.id]:[]}else{const set=new Set(g.defaultOptionIds);e.target.checked?set.add(o.id):set.delete(o.id);g.defaultOptionIds=[...set]}markDirty()};r.querySelector('.choice-remove').onclick=()=>{g.options.splice(oi,1);g.defaultOptionIds=g.defaultOptionIds.filter(id=>id!==o.id);markDirty();renderGroupEditor()}});$('#addChoice').onclick=()=>{g.options.push({id:uid('option'),label:'',price:0});markDirty();renderGroupEditor();setTimeout(()=>$$('.choice-label').at(-1)?.focus(),0)};$('#required').onchange=e=>{g.required=e.target.checked;markDirty()};$('#maxSel')?.addEventListener('input',e=>{g.maxSelections=Math.max(1,Number(e.target.value)||1);markDirty()});$('#deleteGroup').onclick=()=>{if(!confirm(`Slette valggruppen "${g.title||'uten navn'}"? Den fjernes fra alle produkter.`))return;config.optionGroups.splice(gi,1);config.sections.forEach(s=>s.items.forEach(p=>p.optionGroupIds=p.optionGroupIds.filter(id=>id!==g.id)));markDirty();closeEditor();mode==='library'?renderLibrary():renderMenu()}}
function bindTopTools(){const inp=$('#menuSearch');if(inp){inp.value=search;inp.oninput=e=>{search=e.target.value.trim();renderMenu()}}$('#collapseBtn')?.addEventListener('click',()=>{openSection='';renderMenu()})}
$('#addCategoryBtn').onclick=()=>{const s={id:uid('section'),title:'',note:'',items:[]};config.sections.push(s);openSection=s.id;markDirty();renderMenu();editCategory(config.sections.length-1)};$('#closeEditor').onclick=()=>{const ret=editing?.returnTo;closeEditor();if(ret)editProduct(ret.si,ret.pi)};$('#previewBtn').onclick=()=>window.open('index.html','_blank');$('#previewNav').onclick=()=>window.open('index.html','_blank');saveBtn.onclick=()=>save(true);window.addEventListener('beforeunload',e=>{if(!dirty)return;e.preventDefault();e.returnValue=''});
bindTopTools();load();
})();