(()=>{
'use strict';
const DB='https://bestill-19-default-rtdb.europe-west1.firebasedatabase.app';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const arr=v=>Array.isArray(v)?v:(v&&typeof v==='object'?Object.values(v):[]);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ALLERGENS=[['melk','Melk'],['gluten','Gluten'],['egg','Egg'],['soya','Soya'],['selleri','Selleri'],['sennep','Sennep'],['sesam','Sesam'],['fisk','Fisk'],['skalldyr','Skalldyr'],['peanøtter','Peanøtter'],['nøtter','Nøtter'],['sulfitter','Sulfitter']];
let config={sections:[],optionGroups:[]}, openSection='', editing=null, search='', dirty=false, saveTimer=0, saving=false, dragData=null;
const root=$('#menuRoot'), status=$('#saveState'), saveBtn=$('#saveBtn'), editor=$('#editor');
const uid=(p='id')=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)}
function normalize(){
 config.sections=arr(config.sections).map(s=>({...s,id:String(s?.id||uid('section')),items:arr(s?.items)}));
 config.sections.forEach(s=>s.items=s.items.map(p=>{
   const sizes=arr(p?.sizes).map((x,i)=>({id:String(x?.id||uid('size')),label:String(x?.label||x?.name||''),price:Number(x?.price)||0}));
   return {...p,id:String(p?.id||uid('product')),sizes:sizes.length?sizes:[{id:uid('size'),label:'Standard',price:Number(p?.price??p?.mediumPrice)||0}],defaultSizeIndex:Math.max(0,Number(p?.defaultSizeIndex)||0),optionGroupIds:arr(p?.optionGroupIds).map(String),allergens:arr(p?.allergens)};
 }));
 config.optionGroups=arr(config.optionGroups).map(g=>({
   ...g,id:String(g?.id||uid('group')),title:String(g?.title||''),selectionMode:g?.selectionMode==='multiple'?'multiple':'single',required:Boolean(g?.required),maxSelections:Math.max(1,Number(g?.maxSelections)||1),defaultOptionIds:arr(g?.defaultOptionIds).map(String),options:arr(g?.options).map(o=>({id:String(o?.id||uid('option')),label:String(o?.label||''),price:Number(o?.price)||0}))
 }));
}
async function load(){
 try{const r=await fetch(DB+'/.json',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);config=await r.json()||{};normalize();status.textContent='Kaydedildi';render();}
 catch(e){root.innerHTML=`<div class="empty">Menü yüklenemedi: ${esc(e.message)}</div>`;status.textContent='Hata';}
}
function markDirty(){
 dirty=true; status.textContent='Değişiklik var'; status.className='save-state dirty'; saveBtn.disabled=false;
 clearTimeout(saveTimer); saveTimer=setTimeout(()=>save(false),900);
}
async function save(manual=true){
 if(saving||!dirty)return; saving=true; clearTimeout(saveTimer); status.textContent='Kaydediliyor…'; status.className='save-state saving'; saveBtn.disabled=true;
 try{const r=await fetch(DB+'/.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});if(!r.ok)throw Error('HTTP '+r.status);dirty=false;status.textContent='Kaydedildi';status.className='save-state saved';if(manual)toast('Değişiklikler kaydedildi');}
 catch(e){dirty=true;status.textContent='Kaydetme hatası';status.className='save-state error';saveBtn.disabled=false;toast('Kaydedilemedi');}
 finally{saving=false}
}
function pimg(p){return p.imageUrl||p.image||''} function simg(s){return s.imageUrl||s.image||s.items.map(pimg).find(Boolean)||''}
function priceText(p){const v=p.sizes.map(x=>Number(x.price)).filter(Number.isFinite);if(!v.length)return '';const mn=Math.min(...v),mx=Math.max(...v);return mn===mx?`${mn} kr`:`fra ${mn} kr`}
function filterItems(s){if(!search)return s.items;const q=search.toLocaleLowerCase('nb-NO');return s.items.filter(p=>`${p.name||''} ${p.description||p.ingredients||''}`.toLocaleLowerCase('nb-NO').includes(q))}
function render(){root.innerHTML=config.sections.map((s,si)=>sectionHtml(s,si)).join('')||'<div class="empty">Ingen kategorier</div>';bindList();}
function sectionHtml(s,si){const open=search?filterItems(s).length>0:openSection===s.id;if(search&&!filterItems(s).length)return '';const img=simg(s);return `<section class="category" draggable="true" data-si="${si}"><div class="category-head"><span class="cat-drag">⋮⋮</span><div class="cat-image" ${img?`style="background-image:url('${esc(img)}')"`:''}></div><div class="cat-copy"><strong>${esc(s.title||'Yeni kategori')}</strong><small>${esc(s.note||s.description||'Klikk for å åpne')}</small></div><div class="cat-meta"><span class="count">${s.items.length} produkter</span><button class="icon-btn cat-edit" title="Rediger">✎</button><span class="chev">${open?'⌃':'⌄'}</span></div></div><div class="category-body" ${open?'':'hidden'}>${filterItems(s).map(p=>itemHtml(p,si,s.items.indexOf(p))).join('')}<button class="add-item" data-add-product="${si}">+ Legg til produkt</button></div></section>`}
function itemHtml(p,si,pi){const def=p.sizes[Math.min(p.defaultSizeIndex,p.sizes.length-1)],groups=p.optionGroupIds.length,img=pimg(p);return `<article class="item" draggable="true" data-si="${si}" data-pi="${pi}"><span class="drag">≡</span><div class="item-img" ${img?`style="background-image:url('${esc(img)}')"`:''}></div><div class="item-copy"><div class="badges">${def?`<span class="badge green">Standard: ${esc(def.label||'Standard')}</span>`:''}${groups?`<span class="badge orange">${groups} valggruppe${groups>1?'r':''}</span>`:''}${p.hidden?'<span class="badge gray">Skjult</span>':''}${p.soldOut?'<span class="badge red">Utsolgt</span>':''}</div><strong>${esc(p.name||'Nytt produkt')}</strong><small>${esc(p.description||p.ingredients||'')}</small></div><div class="item-price">${esc(priceText(p))}</div><div class="item-actions"><button class="mini-action add-group-direct" title="Legg til valggruppe">+ Valg</button><button class="icon-btn item-edit" title="Rediger">✎</button><button class="icon-btn item-more" title="Mer">⋯</button></div></article>`}
function bindList(){
 $$('.category-head').forEach(h=>h.onclick=e=>{if(e.target.closest('button,.cat-drag'))return;const si=+h.closest('.category').dataset.si;openSection=openSection===config.sections[si].id?'':config.sections[si].id;render()});
 $$('.cat-edit').forEach(b=>b.onclick=e=>{e.stopPropagation();editCategory(+b.closest('.category').dataset.si)});
 $$('.item-edit').forEach(b=>b.onclick=()=>{const a=b.closest('.item');editProduct(+a.dataset.si,+a.dataset.pi)});
 $$('.add-group-direct').forEach(b=>b.onclick=()=>{const a=b.closest('.item');editProduct(+a.dataset.si,+a.dataset.pi,true)});
 $$('[data-add-product]').forEach(b=>b.onclick=()=>addProduct(+b.dataset.addProduct));
 $$('.item-more').forEach(b=>b.onclick=()=>{const a=b.closest('.item'),si=+a.dataset.si,pi=+a.dataset.pi,p=config.sections[si].items[pi];if(confirm(`Dupliser ${p.name||'produkt'}?`)){const c=structuredClone(p);c.id=uid('product');c.name=(c.name||'Produkt')+' – kopi';config.sections[si].items.splice(pi+1,0,c);markDirty();render()}});
 bindDrag();
}
function bindDrag(){
 $$('.category').forEach(cat=>{cat.ondragstart=e=>{if(!e.target.closest('.cat-drag')&&e.target!==cat){e.preventDefault();return}dragData={type:'cat',si:+cat.dataset.si};cat.classList.add('dragging')};cat.ondragend=()=>cat.classList.remove('dragging');cat.ondragover=e=>{if(dragData?.type==='cat'){e.preventDefault();cat.classList.add('drag-over')}};cat.ondragleave=()=>cat.classList.remove('drag-over');cat.ondrop=e=>{cat.classList.remove('drag-over');if(dragData?.type!=='cat')return;const to=+cat.dataset.si,from=dragData.si;if(from!==to){const [m]=config.sections.splice(from,1);config.sections.splice(to,0,m);markDirty();render()}}});
 $$('.item').forEach(item=>{item.ondragstart=e=>{if(!e.target.closest('.drag')&&e.target!==item){e.preventDefault();return}dragData={type:'item',si:+item.dataset.si,pi:+item.dataset.pi};item.classList.add('dragging')};item.ondragend=()=>item.classList.remove('dragging');item.ondragover=e=>{if(dragData?.type==='item'){e.preventDefault();item.classList.add('drag-over')}};item.ondragleave=()=>item.classList.remove('drag-over');item.ondrop=e=>{item.classList.remove('drag-over');if(dragData?.type!=='item')return;const tsi=+item.dataset.si,tpi=+item.dataset.pi,{si:fsi,pi:fpi}=dragData;const [m]=config.sections[fsi].items.splice(fpi,1);config.sections[tsi].items.splice(tpi,0,m);markDirty();render()}});
 $$('.category-body').forEach(body=>{body.ondragover=e=>{if(dragData?.type==='item')e.preventDefault()};body.ondrop=e=>{if(dragData?.type!=='item'||e.target.closest('.item'))return;const tsi=+body.closest('.category').dataset.si,{si:fsi,pi:fpi}=dragData;const [m]=config.sections[fsi].items.splice(fpi,1);config.sections[tsi].items.push(m);markDirty();render()}})
}
function openEditor(title,sub='PRODUKTINNSTILLINGER'){editing=editing||{};$('#app').classList.add('editor-open');$('#editorTitle').textContent=title;$('#editorEyebrow').textContent=sub}
function closeEditor(){editing=null;$('#app').classList.remove('editor-open');$('#editorBody').innerHTML=''}
function card(title,body,sub=''){return `<section class="editor-card"><div class="editor-card-head"><h4>${esc(title)}</h4>${sub?`<small>${esc(sub)}</small>`:''}</div><div class="editor-card-body">${body}</div></section>`}
function editCategory(si){const s=config.sections[si];editing={type:'category',si};openEditor('Kategoriinnstillinger','KATEGORI');$('#editorBody').innerHTML=card('Kategori',`<label class="field"><span>Navn</span><input id="catTitle" placeholder="F.eks. Pizza" value="${esc(s.title||'')}"></label><label class="field"><span>Beskrivelse</span><textarea id="catNote" placeholder="Kort beskrivelse">${esc(s.note||s.description||'')}</textarea></label><label class="field"><span>Bilde-URL</span><input id="catImage" placeholder="https://…" value="${esc(s.imageUrl||'')}"></label>`)+card('Handlinger',`<button class="danger-wide" id="deleteCat">Slett kategori</button>`);$('#catTitle').oninput=e=>{s.title=e.target.value;markDirty();render()};$('#catNote').oninput=e=>{s.note=e.target.value;markDirty();render()};$('#catImage').oninput=e=>{s.imageUrl=e.target.value;markDirty();render()};$('#deleteCat').onclick=()=>{if(confirm('Slette kategorien og alle produktene?')){config.sections.splice(si,1);markDirty();closeEditor();render()}}}
function addProduct(si){const p={id:uid('product'),name:'',description:'',imageUrl:'',sizes:[{id:uid('size'),label:'',price:0}],defaultSizeIndex:0,allergens:[],optionGroupIds:[],hidden:false,soldOut:false};config.sections[si].items.push(p);openSection=config.sections[si].id;markDirty();render();editProduct(si,config.sections[si].items.length-1)}
function editProduct(si,pi,focusGroup=false){editing={type:'product',si,pi};openEditor(config.sections[si].items[pi].name||'Nytt produkt');renderProductEditor();if(focusGroup)setTimeout(()=>$('#addGroup')?.click(),40)}
function renderProductEditor(){const {si,pi}=editing,p=config.sections[si].items[pi],linked=new Set(p.optionGroupIds);$('#editorBody').innerHTML=
 card('Grunninformasjon',`<label class="field"><span>Produktnavn</span><input id="pName" placeholder="F.eks. 3 - Al Capone" value="${esc(p.name||'')}"></label><label class="field"><span>Beskrivelse</span><textarea id="pDesc" placeholder="Ingredienser og kort beskrivelse">${esc(p.description||p.ingredients||'')}</textarea></label><label class="field"><span>Bilde-URL</span><input id="pImage" placeholder="https://…" value="${esc(p.imageUrl||p.image||'')}"></label>`)+
 card('Størrelser og priser',`<div class="size-head"><span>Valgt</span><span>Størrelse</span><span>Pris</span><span></span></div><div id="sizeRows">${p.sizes.map((s,i)=>sizeRow(s,i,p.defaultSizeIndex)).join('')}</div><button class="add-line" id="addSize">+ Legg til størrelse</button><p class="hint">Den markerte størrelsen er valgt når kunden åpner produktet.</p>`,'Velg standard')+
 card('Allergener',`<div class="chips">${ALLERGENS.map(([id,l])=>`<label class="chip-check"><input type="checkbox" data-allergen="${id}" ${p.allergens.includes(id)?'checked':''}>${l}</label>`).join('')}</div>`)+
 card('Tillegg og valg',`<div id="groups">${config.optionGroups.filter(g=>linked.has(g.id)).map(groupHtml).join('')||'<p class="hint">Ingen valggrupper. Legg til saus, topping, styrke eller andre valg kunden skal se.</p>'}</div><button class="primary-line" id="addGroup">+ Legg til valggruppe</button>`,'Vises til kunden')+
 card('Tilgjengelighet',`<label class="toggle-row"><span><strong>Vis produktet</strong><small>Skjul uten å slette</small></span><span class="switch"><input id="visible" type="checkbox" ${p.hidden?'':'checked'}><i></i></span></label><label class="toggle-row"><span><strong>Utsolgt</strong><small>Kunden kan ikke bestille</small></span><span class="switch"><input id="sold" type="checkbox" ${p.soldOut?'checked':''}><i></i></span></label>`)+
 card('Mer',`<button class="quiet" id="duplicate">Dupliser produkt</button> <button class="danger-wide" id="deleteProduct">Slett produkt</button>`);
 bindProductEditor();}
function sizeRow(s,i,d){return `<div class="size-row" data-i="${i}"><label><input type="radio" name="defsize" ${i===d?'checked':''}></label><input class="sl" placeholder="F.eks. Stor" value="${esc(s.label||'')}"><input class="sp" type="number" min="0" placeholder="0" value="${Number(s.price)||''}"><button class="remove-mini sr">×</button></div>`}
function groupHtml(g){const multi=g.selectionMode==='multiple',defs=new Set(g.defaultOptionIds);return `<div class="group-card" data-gid="${esc(g.id)}"><div class="group-head"><input class="gt" placeholder="F.eks. Velg saus" value="${esc(g.title||'')}"><button class="remove-mini unlink">×</button></div><div class="group-body"><div class="choice-mode"><button class="mode ${!multi?'active':''}" data-mode="single">○ Ett valg</button><button class="mode ${multi?'active':''}" data-mode="multiple">☑ Flere valg</button></div><p class="group-help">${multi?'Kunden kan velge flere alternativer.':'Kunden kan velge ett alternativ.'} Marker under hvilket valg som skal være valgt fra start.</p><div class="choice-head"><span>Start</span><span>Alternativ</span><span>+ pris</span><span></span></div>${g.options.map((o,i)=>`<div class="choice-row" data-i="${i}"><label><input class="od" type="${multi?'checkbox':'radio'}" name="def-${esc(g.id)}" ${defs.has(o.id)?'checked':''}></label><input class="ol" placeholder="F.eks. Mild" value="${esc(o.label||'')}"><input class="op" type="number" min="0" placeholder="0" value="${Number(o.price)||''}"><button class="remove-mini or">×</button></div>`).join('')}<button class="add-line add-option">+ Legg til alternativ</button><div class="rule-box"><label class="toggle-row"><span><strong>Zorunlu valg</strong><small>Kunden må velge før produktet kan legges i kurven</small></span><span class="switch"><input class="required" type="checkbox" ${g.required?'checked':''}><i></i></span></label>${multi?`<label class="field"><span>Maks antall kunden kan velge</span><input class="max" type="number" min="1" value="${g.maxSelections||1}"></label>`:''}</div><button class="danger-link delete-group">Slett gruppen helt</button></div></div>`}
function bindProductEditor(){const {si,pi}=editing,p=config.sections[si].items[pi];$('#pName').oninput=e=>{p.name=e.target.value;$('#editorTitle').textContent=p.name||'Nytt produkt';markDirty();render()};$('#pDesc').oninput=e=>{p.description=e.target.value;delete p.ingredients;markDirty();render()};$('#pImage').oninput=e=>{p.imageUrl=e.target.value;delete p.image;markDirty();render()};$$('.size-row').forEach(r=>{const i=+r.dataset.i;r.querySelector('input[type=radio]').onchange=()=>{p.defaultSizeIndex=i;markDirty();render()};r.querySelector('.sl').oninput=e=>{p.sizes[i].label=e.target.value;markDirty();render()};r.querySelector('.sp').oninput=e=>{p.sizes[i].price=Number(e.target.value)||0;markDirty();render()};r.querySelector('.sr').onclick=()=>{if(p.sizes.length===1)return toast('Minst én størrelse må kalmalıdır');p.sizes.splice(i,1);p.defaultSizeIndex=Math.min(p.defaultSizeIndex,p.sizes.length-1);markDirty();renderProductEditor();render()}});$('#addSize').onclick=()=>{p.sizes.push({id:uid('size'),label:'',price:0});markDirty();renderProductEditor()};$$('[data-allergen]').forEach(c=>c.onchange=e=>{const s=new Set(p.allergens);e.target.checked?s.add(e.target.dataset.allergen):s.delete(e.target.dataset.allergen);p.allergens=[...s];markDirty()});$('#addGroup').onclick=()=>{const g={id:uid('group'),title:'',selectionMode:'single',required:false,maxSelections:1,defaultOptionIds:[],options:[{id:uid('option'),label:'',price:0}]};config.optionGroups.push(g);p.optionGroupIds.push(g.id);markDirty();renderProductEditor();setTimeout(()=>$$('.group-card').at(-1)?.querySelector('.gt')?.focus(),0)};bindGroups();$('#visible').onchange=e=>{p.hidden=!e.target.checked;markDirty();render()};$('#sold').onchange=e=>{p.soldOut=e.target.checked;markDirty();render()};$('#duplicate').onclick=()=>{const c=structuredClone(p);c.id=uid('product');c.name=(c.name||'Produkt')+' – kopi';config.sections[si].items.splice(pi+1,0,c);markDirty();render();toast('Duplisert')};$('#deleteProduct').onclick=()=>{if(confirm('Slette produktet?')){config.sections[si].items.splice(pi,1);markDirty();closeEditor();render()}}}
function bindGroups(){const p=config.sections[editing.si].items[editing.pi];$$('.group-card').forEach(card=>{const g=config.optionGroups.find(x=>x.id===card.dataset.gid);if(!g)return;card.querySelector('.gt').oninput=e=>{g.title=e.target.value;markDirty()};card.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{g.selectionMode=b.dataset.mode;g.maxSelections=g.selectionMode==='single'?1:Math.max(1,g.maxSelections);g.defaultOptionIds=g.selectionMode==='single'?g.defaultOptionIds.slice(0,1):g.defaultOptionIds;markDirty();renderProductEditor()});card.querySelector('.required').onchange=e=>{g.required=e.target.checked;markDirty()};card.querySelector('.max')?.addEventListener('input',e=>{g.maxSelections=Math.max(1,Number(e.target.value)||1);g.defaultOptionIds=g.defaultOptionIds.slice(0,g.maxSelections);markDirty()});card.querySelector('.add-option').onclick=()=>{g.options.push({id:uid('option'),label:'',price:0});markDirty();renderProductEditor()};card.querySelector('.unlink').onclick=()=>{p.optionGroupIds=p.optionGroupIds.filter(id=>id!==g.id);markDirty();renderProductEditor();render()};card.querySelector('.delete-group').onclick=()=>{if(!confirm('Bu valggruppesi tüm ürünlerden silinsin mi?'))return;config.optionGroups=config.optionGroups.filter(x=>x.id!==g.id);config.sections.forEach(s=>s.items.forEach(x=>x.optionGroupIds=x.optionGroupIds.filter(id=>id!==g.id)));markDirty();renderProductEditor();render()};card.querySelectorAll('.choice-row').forEach(row=>{const i=+row.dataset.i,o=g.options[i];row.querySelector('.ol').oninput=e=>{o.label=e.target.value;markDirty()};row.querySelector('.op').oninput=e=>{o.price=Number(e.target.value)||0;markDirty()};row.querySelector('.od').onchange=e=>{if(g.selectionMode==='single')g.defaultOptionIds=e.target.checked?[o.id]:[];else{const s=new Set(g.defaultOptionIds);e.target.checked?s.add(o.id):s.delete(o.id);g.defaultOptionIds=[...s].slice(0,g.maxSelections)}markDirty()};row.querySelector('.or').onclick=()=>{g.options.splice(i,1);g.defaultOptionIds=g.defaultOptionIds.filter(id=>id!==o.id);markDirty();renderProductEditor()}})})}
$('#saveBtn').onclick=()=>save(true);$('#closeEditor').onclick=closeEditor;$('#previewBtn').onclick=()=>window.open('index.html','_blank');$('#previewNav').onclick=()=>window.open('index.html','_blank');$('#menuSearch').oninput=e=>{search=e.target.value.trim();render()};$('#collapseBtn').onclick=()=>{openSection='';render()};$('#addCategoryBtn').onclick=()=>{const s={id:uid('section'),title:'',note:'',items:[]};config.sections.push(s);openSection=s.id;markDirty();render();editCategory(config.sections.length-1)};window.addEventListener('beforeunload',e=>{if(!dirty)return;e.preventDefault();e.returnValue=''});load();
})();